my_machine:
  hosts:
    xps15:
      ansible_connection: local
      ansible_user: jflabonte
      ansible_password: "{{ jflabonte_password  }}"
      ansible_become_password: "{{ xps15_root_password  }}" 
      ansible_become_method: su
