---
# defaults file for roles/initial_setup

base_dependencies:
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - weechat
  - python3
  - python3-pip
  - python3-dev
  - build-essential
  - rsync
  - cmake
  - wget
  - curl
  - snapd
  - virtualbox
  - gimp
  - inkscape
  - vagrant
  - sshpass
  - firefox
  - zsh
  - dkms
  - tmux
  - neofetch
  - gdebi
  - git
  - pass
  - intel-media-va-driver-non-free
  - qtpass
  - git-lfs
  - git
  - peek
  - snapd

wanted_applications:
  - calibre
  - nmap
  - wireshark
  - restic
