---
# tasks file for roles/initial_setup

- name: Install Linux-Headers on Debian
  shell: apt-get install linux-headers-$(uname -r|sed 's/[^-]*-[^-]*-//')
  become: yes

- name: Install Dependencies
  apt:
    name: "{{ base_dependencies  }}"
    state: latest
  become: yes

- name: Add keys for new repos
  shell: "{{ item.add_key_cmd }}" 
  with_items: "{{ third_party_repos }}"
  become: true

- name: Add Third Party Repo
  shell: "{{ item.add_repo_cmd  }}"
  with_items: "{{ third_party_repos }}"
  become: yes

- name: Install Third Party Package
  apt:
    update_cache: yes
    name: "{{ item.name }}"
    state: latest
  with_items: "{{ third_party_repos }}"
  become: yes

- name: Create folder if it doesn't exists
  file:
    path: "{{ deb_folder }}"
    state: directory
    mode: '755'

- name: Download Applications Deb
  get_url:
    url: "{{ item.url }}"
    dest: "{{ deb_folder  }}/{{ item.name }}"
  with_items: "{{ deb_packages_to_fetch }}"

- name: Install .deb archives
  apt:
    deb: "{{ deb_folder}}/{{ item.name }}"
    state: present
  with_items: "{{ deb_packages_to_fetch }}"
  become: yes

- name: Remove deb folder
  file:
    path: "{{ deb_folder }}"
    state: absent
