---
# tasks file for roles/initial_setup

- name: Install Dependencies
  apt:
    name: "{{ base_dependencies }}"
    update_cache: yes
    state: latest
  become: yes

- name: Install wanted applications
  apt:
    name: "{{ wanted_applications }}"
    update_cache: yes
    state: latest
  become: yes

- name: Install Snaps
  snap:
    name: "{{ item.name }}"
    state: present
    channel: "{{ item.channel }}"
    classic: "{{ item.classic }}"
  with_items: "{{ snaps_to_install }}"
  become: true

- name: Update, Upgrade, Autoremove, Autoclean
  apt:
    update_cache: yes
    upgrade: yes
    autoclean: yes
    autoremove: yes
  become: yes

- name: Install new sudoers
  copy:
    src: sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 400
  become: yes
